var mem = new Uint8Array(30000);
var r = 0;
var buf = '';
var pc = [];
function putchar() { process.stdout.write(String.fromCharCode(mem[r]))};
function getchar() { if (buf.length == 0) return false; mem[r] = buf.charCodeAt(0); buf = buf.substring(1); return true; }
;function main() {
switch (pc.pop()) {
default:
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
while (mem[r]) { /* [ */
r++; /* > */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
r++; /* > */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
r++; /* > */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
r--; /* < */
r--; /* < */
r--; /* < */
mem[r]--; /* - */
}; /* ] */
r++; /* > */
putchar(); /* . */
r++; /* > */
mem[r]++; /* + */
mem[r]++; /* + */
putchar(); /* . */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
putchar(); /* . */
putchar(); /* . */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
putchar(); /* . */
r++; /* > */
mem[r]--; /* - */
putchar(); /* . */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
putchar(); /* . */
r--; /* < */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
putchar(); /* . */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
putchar(); /* . */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
putchar(); /* . */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
putchar(); /* . */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
putchar(); /* . */
r++; /* > */
mem[r]++; /* + */
putchar(); /* . */
};
};
main();
