var mem = new Uint8Array(30000);
var r = 0;
var buf = '';
function main() {
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
while (mem[r]) { /* [ */
r++; /* > */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
r++; /* > */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
r++; /* > */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
r--; /* < */
r--; /* < */
r--; /* < */
mem[r]--; /* - */
}; /* ] */
r++; /* > */
process.stdout.write(String.fromCharCode(mem[r])); /* . */
r++; /* > */
mem[r]++; /* + */
mem[r]++; /* + */
process.stdout.write(String.fromCharCode(mem[r])); /* . */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
process.stdout.write(String.fromCharCode(mem[r])); /* . */
process.stdout.write(String.fromCharCode(mem[r])); /* . */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
process.stdout.write(String.fromCharCode(mem[r])); /* . */
r++; /* > */
mem[r]--; /* - */
process.stdout.write(String.fromCharCode(mem[r])); /* . */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
process.stdout.write(String.fromCharCode(mem[r])); /* . */
r--; /* < */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
process.stdout.write(String.fromCharCode(mem[r])); /* . */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
process.stdout.write(String.fromCharCode(mem[r])); /* . */
mem[r]++; /* + */
mem[r]++; /* + */
mem[r]++; /* + */
process.stdout.write(String.fromCharCode(mem[r])); /* . */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
process.stdout.write(String.fromCharCode(mem[r])); /* . */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
mem[r]--; /* - */
process.stdout.write(String.fromCharCode(mem[r])); /* . */
r++; /* > */
mem[r]++; /* + */
process.stdout.write(String.fromCharCode(mem[r])); /* . */
};
main();
